In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

df = pd.read_csv("./Datasets/winequality-red.csv", ';') 
columns = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
          'free sulfur dioxide', 'total sulfur dioxide', 'density', 'ph', 'sulphates', 'alcohol', 'quality']

In [26]:
for index, row in df.iterrows():
    if row['quality'] <= 5:
        df.iloc[index, -1] = 0
    elif row['quality'] >= 6 and row['quality'] <= 7:
        df.iloc[index, -1] = 1
    elif row['quality'] >= 8:
        df.iloc[index, -1] = 2
     

In [27]:
df.head(1).transpose()

0
fixed acidity          7.4000
volatile acidity       0.7000
citric acid            0.0000
residual sugar         1.9000
chlorides              0.0760
free sulfur dioxide   11.0000
total sulfur dioxide  34.0000
density                0.9978
pH                     3.5100
sulphates              0.5600
alcohol                9.4000
quality                0.0000

In [28]:
df.describe().transpose()

count       mean        std      min      25%  \
fixed acidity         1599.0   8.319637   1.741096  4.60000   7.1000   
volatile acidity      1599.0   0.527821   0.179060  0.12000   0.3900   
citric acid           1599.0   0.270976   0.194801  0.00000   0.0900   
residual sugar        1599.0   2.538806   1.409928  0.90000   1.9000   
chlorides             1599.0   0.087467   0.047065  0.01200   0.0700   
free sulfur dioxide   1599.0  15.874922  10.460157  1.00000   7.0000   
total sulfur dioxide  1599.0  46.467792  32.895324  6.00000  22.0000   
density               1599.0   0.996747   0.001887  0.99007   0.9956   
pH                    1599.0   3.311113   0.154386  2.74000   3.2100   
sulphates             1599.0   0.658149   0.169507  0.33000   0.5500   
alcohol               1599.0  10.422983   1.065668  8.40000   9.5000   
quality               1599.0   0.545966   0.520164  0.00000   0.0000   

                           50%        75%        max  
fixed acidity          7.90000   9.200000   15.90000  
volatile acidity       0.52000   0.640000    1.58000  
citric acid            0.26000   0.420000    1.00000  
residual sugar         2.20000   2.600000   15.50000  
chlorides              0.07900   0.090000    0.61100  
free sulfur dioxide   14.00000  21.000000   72.00000  
total sulfur dioxide  38.00000  62.000000  289.00000  
density                0.99675   0.997835    1.00369  
pH                     3.31000   3.400000    4.01000  
sulphates              0.62000   0.730000    2.00000  
alcohol               10.20000  11.100000   14.90000  
quality                1.00000   1.000000    2.00000

In [29]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values


In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [32]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[108  57   0]
 [ 29 122   1]
 [  2   1   0]]
              precision    recall  f1-score   support

           0       0.78      0.65      0.71       165
           1       0.68      0.80      0.73       152
           2       0.00      0.00      0.00         3

    accuracy                           0.72       320
   macro avg       0.48      0.49      0.48       320
weighted avg       0.72      0.72      0.72       320



In [33]:
### MLP Perceptron
model = Sequential()
model.add(Dense(12, input_shape=(11,), activation='relu'))
model.add(Dense(12*12, activation='relu'))
model.add(Dense(12*12, activation='relu'))
model.add(Dense(1, activation='relu'))

# Configure the model and start training
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=1)

# Test the model after training
test_results = model.evaluate(X_test, y_test, verbose=1)
print(f'Test results - Loss: {test_results[0]} - Accuracy: {test_results[1]}%')

Epoch 1/100
128/128 [==============================] - 0s 882us/step - loss: 0.5735 - accuracy: 0.4624
Epoch 2/100
128/128 [==============================] - 0s 943us/step - loss: 0.6077 - accuracy: 0.4311
Epoch 3/100
128/128 [==============================] - 0s 934us/step - loss: 0.5649 - accuracy: 0.4677
Epoch 4/100
128/128 [==============================] - 0s 1ms/step - loss: 0.5716 - accuracy: 0.4530
Epoch 5/100
128/128 [==============================] - 0s 1ms/step - loss: 0.5840 - accuracy: 0.4442
Epoch 6/100
128/128 [==============================] - 0s 1ms/step - loss: 0.5956 - accuracy: 0.4462
Epoch 7/100
128/128 [==============================] - 0s 879us/step - loss: 0.5930 - accuracy: 0.4520
Epoch 8/100
128/128 [==============================] - 0s 1ms/step - loss: 0.6165 - accuracy: 0.4405
Epoch 9/100
128/128 [==============================] - 0s 715us/step - loss: 0.5776 - accuracy: 0.4631
Epoch 10/100
128/128 [==============================] - 0s 719us/step - loss: 0.5

In [34]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred6 = clf.predict(X_test)
print(classification_report(y_test, y_pred6))

              precision    recall  f1-score   support

           0       0.82      0.67      0.74       165
           1       0.69      0.83      0.75       152
           2       0.33      0.33      0.33         3

    accuracy                           0.74       320
   macro avg       0.61      0.61      0.61       320
weighted avg       0.75      0.74      0.74       320



In [35]:
# Best choice Random Forest
classifier = RandomForestClassifier(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.87      0.76      0.81       165
           1       0.76      0.88      0.81       152
           2       1.00      0.33      0.50         3

    accuracy                           0.81       320
   macro avg       0.88      0.66      0.71       320
weighted avg       0.82      0.81      0.81       320



In [36]:
### Creation of a ML model
from joblib import dump, load
classifier = RandomForestClassifier(random_state=0)
classifier.fit(X, y)

dump(classifier, 'classifier/redClassifier.joblib') 

['classifier/redClassifier.joblib']

In [37]:
import requests

url = "http://localhost:5000/predict/wine/red?fixed acidity=7.7&volatile acidity=0.2&citric acid=0.1&residual sugar=2&chlorides=0.0760&free sulfur dioxide=15.0&total sulfur dioxide=34&density=5&ph=3.5100&sulphates=0.100&alcohol=17"

payload = {}
headers= {}

response = requests.request("POST", url, headers=headers, data = payload)

print(response.text.encode('utf8'))


b'good'
