In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

df = pd.read_csv("./Datasets/winequality-white.csv", ';') 
columns = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
          'free sulfur dioxide', 'total sulfur dioxide', 'density', 'ph', 'sulphates', 'alcohol', 'quality']

In [2]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [3]:
df.describe().transpose()

count        mean        std      min         25%  \
fixed acidity         4898.0    6.854788   0.843868  3.80000    6.300000   
volatile acidity      4898.0    0.278241   0.100795  0.08000    0.210000   
citric acid           4898.0    0.334192   0.121020  0.00000    0.270000   
residual sugar        4898.0    6.391415   5.072058  0.60000    1.700000   
chlorides             4898.0    0.045772   0.021848  0.00900    0.036000   
free sulfur dioxide   4898.0   35.308085  17.007137  2.00000   23.000000   
total sulfur dioxide  4898.0  138.360657  42.498065  9.00000  108.000000   
density               4898.0    0.994027   0.002991  0.98711    0.991723   
pH                    4898.0    3.188267   0.151001  2.72000    3.090000   
sulphates             4898.0    0.489847   0.114126  0.22000    0.410000   
alcohol               4898.0   10.514267   1.230621  8.00000    9.500000   
quality               4898.0    5.877909   0.885639  3.00000    5.000000   

                            50%       75%        max  
fixed acidity           6.80000    7.3000   14.20000  
volatile acidity        0.26000    0.3200    1.10000  
citric acid             0.32000    0.3900    1.66000  
residual sugar          5.20000    9.9000   65.80000  
chlorides               0.04300    0.0500    0.34600  
free sulfur dioxide    34.00000   46.0000  289.00000  
total sulfur dioxide  134.00000  167.0000  440.00000  
density                 0.99374    0.9961    1.03898  
pH                      3.18000    3.2800    3.82000  
sulphates               0.47000    0.5500    1.08000  
alcohol                10.40000   11.4000   14.20000  
quality                 6.00000    6.0000    9.00000

In [26]:
for index, row in df.iterrows():
    if row['quality'] <= 5:
        df.iloc[index, -1] = 0
    elif row['quality'] >= 6 and row['quality'] <= 7:
        df.iloc[index, -1] = 1
    elif row['quality'] >= 8:
        df.iloc[index, -1] = 2
     

In [27]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [30]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[198  96   1]
 [114 522  10]
 [  4  31   4]]
              precision    recall  f1-score   support

           0       0.63      0.67      0.65       295
           1       0.80      0.81      0.81       646
           2       0.27      0.10      0.15        39

    accuracy                           0.74       980
   macro avg       0.57      0.53      0.53       980
weighted avg       0.73      0.74      0.73       980



In [31]:
### MLP Perceptron
model = Sequential()
model.add(Dense(12, input_shape=(11,), activation='relu'))
model.add(Dense(12*12, activation='relu'))
model.add(Dense(12*12, activation='relu'))
model.add(Dense(1, activation='relu'))

# Configure the model and start training
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=1)

# Test the model after training
test_results = model.evaluate(X_test, y_test, verbose=1)
print(f'Test results - Loss: {test_results[0]} - Accuracy: {test_results[1]}%')

Epoch 1/100
392/392 [==============================] - 1s 794us/step - loss: 0.2931 - accuracy: 0.6272
Epoch 2/100
392/392 [==============================] - 0s 892us/step - loss: 0.2000 - accuracy: 0.7275
Epoch 3/100
392/392 [==============================] - 0s 1ms/step - loss: 0.1942 - accuracy: 0.7402
Epoch 4/100
392/392 [==============================] - 0s 910us/step - loss: 0.2014 - accuracy: 0.7298
Epoch 5/100
392/392 [==============================] - 0s 1ms/step - loss: 0.1985 - accuracy: 0.7356
Epoch 6/100
392/392 [==============================] - 0s 925us/step - loss: 0.1755 - accuracy: 0.7647
Epoch 7/100
392/392 [==============================] - 0s 1ms/step - loss: 0.1840 - accuracy: 0.7355
Epoch 8/100
392/392 [==============================] - 0s 919us/step - loss: 0.1768 - accuracy: 0.7662
Epoch 9/100
392/392 [==============================] - 0s 825us/step - loss: 0.1681 - accuracy: 0.7625
Epoch 10/100
392/392 [==============================] - 0s 811us/step - loss: 0

In [32]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred6 = clf.predict(X_test)
print(classification_report(y_test, y_pred6))

              precision    recall  f1-score   support

           0       0.68      0.75      0.71       295
           1       0.85      0.81      0.83       646
           2       0.33      0.36      0.35        39

    accuracy                           0.77       980
   macro avg       0.62      0.64      0.63       980
weighted avg       0.78      0.77      0.77       980



In [33]:
# Best choice Random Forest
classifier = RandomForestClassifier(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.76      0.73      0.74       295
           1       0.85      0.90      0.87       646
           2       0.85      0.28      0.42        39

    accuracy                           0.82       980
   macro avg       0.82      0.63      0.68       980
weighted avg       0.82      0.82      0.81       980



In [34]:
### Creation of a ML model
from joblib import dump, load
classifier = RandomForestClassifier(random_state=0)
classifier.fit(X, y)

dump(classifier, 'classifier/whiteClassifier.joblib') 

['classifier/whiteClassifier.joblib']